# Integración continua Travis CI

# Lenguaje de programación

language: cpp

# Sistema operativo destino a probar

os: linux

# Distribución del sistema operativo

dist: trusty

# Requerimiento de permisos en Linux

sudo: enabled

# Compiladores a emplear

compiler: 
#  - gcc
   - clang

# Tareas a realizar antes de instalacción

before_install:

# Actualizar

  - sudo apt-get -qq update

# Configurar Git si no lo está

  - if [ ! `git config --get user.email` ]; then `git config --global user.email 'user@example.com'`; fi
  - if [ ! `git config --get user.name` ]; then `git config --global user.name 'Travis CI'`; fi

# En caso de requerir instalar algo para la prueba

install:

# Instalar YARP

  - sudo apt-get install libeigen3-dev

# Instalar OpenCV

  - sudo apt-get install libopencv-dev

# Tareas a ejecutar antes de nuestra prueba

before_script:
  - cd programs
  - cd YARP_Streaming_Control_Emisor
  - mkdir build
  - cd build
  - cmake ..

# Compilamos

script:
  - make

# En caso de compilación exitosa

after_success:
  - sudo make install
  - ./emisor_control
  - sudo make uninstall

# Notificaciones por correo

notifications:
email: true
